# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - hugo
      - cp -r public/* docs/
    silent: true

  serve:
    cmds:
      - hugo server -D
    silent: true

  clean:
    cmds:
      - rm -rf public
      - rm -rf docs/*
    silent: true

  new-post:
    cmds:
      - hugo new "content/posts/{{.CLI_ARGS}}.md" -k posts
    silent: true