# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - hugo
      - cp -r public/* docs/
    silent: true
  serve:
    cmds:
      - hugo server -D
    silent: true
